table-mapping:
  tables:

    # =========================================================
    # ROOT → CLAIM HISTORY
    # =========================================================
    CLAIM_HISTORY:

      tableName: CLAIM_HISTORY
      guidColumn: id
      skipIfEmpty: false

      columns:

        claimNum:
          identifiers:
            - TPCR_ID

        eventTypeCd:
          identifiers:
            - TPCR_ID

        eventSubTypeCd:
          identifiers:
            - TPCR_STATUS

        claimTypeCd:
          identifiers:
            - TPCR_CASE_TYPE

        clmAge:
          identifiers:
            - TPCR_DECEASED_AGE

        statusCd:
          identifiers:
            - TPCR_STATUS

        byPassSysConsideredFl:
          identifiers:
            - TPCR_BYPASS_SYS_CONSIDERED_FL

        claimCurrencyCd:
          identifiers:
            - TPCR_INSURERCODE

        approvedAmtPolCurrency:
          identifiers:
            - TPCR_INSURERCODE

        approvedAmtClmCurrency:
          identifiers:
            - TPCR_INSURERCODE

        totSpecialBonusAmt:
          identifiers:
            - TPCR_INSURERCODE

        totLifeTimeAmt:
          identifiers:
            - TPCR_INSURERCODE

        totDeductibleAmt:
          identifiers:
            - TPCR_INSURERCODE

        totReductionAmt:
          identifiers:
            - TPCR_INSURERCODE

        totDeductedAmt:
          identifiers:
            - TPCR_INSURERCODE

        totDedCreditAdjAmt:
          identifiers:
            - TPCR_INSURERCODE

        totRoomAdjAmt:
          identifiers:
            - TPCR_INSURERCODE

        totCoInsuranceAmt:
          identifiers:
            - TPCR_INSURERCODE

        totAmtPaidByExternal:
          identifiers:
            - TPCR_INSURERCODE

        totAmtPaidByExternalIFPHosp:
          identifiers:
            - TPCR_INSURERCODE

        vhisStandardFl:
          identifiers:
            - TPCR_INSURERCODE

        errorFl:
          identifiers:
            - TPCR_INSURERCODE

        claimGuid:
          identifiers:
            - id

        migratedSourceCd:
          identifiers:
            - TPCR_INSURERCODE


        versionId:
          identifiers:
            - TPCR_INSURERCODE

        guid:
          identifiers:
            - id

        createdDt:
          identifiers:
            - TPCR_CREATED_DT

        updatedDt:
          identifiers:
            - TPCR_UPDATED_DT

        createdUser:
          identifiers:
            - TPCR_CREATED_BY

        updatedUser:
          identifiers:
            - TPCR_UPDATED_BY

        baseCompanyCd:
          identifiers:
            - TPCR_UPDATED_BY

        baseCountryCd:
          identifiers:
            - TPCR_UPDATED_BY

        versionNum:
          identifiers:
            - TPCR_UPDATED_BY

        workflowStatusCd:
          identifiers:
            - TPCR_UPDATED_BY

        shareByRegionalOfc:
          identifiers:
            - TPCR_UPDATED_BY


      children:
        - CLAIM_HISTORY_POLICY

    # =========================================================
    # CLAIM CLIENT (CLAIMANT / NOMINEE)
    # =========================================================
    CLAIM_HISTORY_CLIENT:

      tableName: CLAIM_HISTORY_CLIENT

      parent: CLAIM_HISTORY
      parentGuidRef: claim_history_ref_guid
      guidColumn: id

      skipIfEmpty: true

      columns:

        roleCd:
          identifiers:
            - TPCR_REL_TYPE

        clientCd:
          identifiers:
            - TPCR_CUST_ID

        clientRefGuid:
          identifiers:
            - id

        claim_history_ref_guid:
          identifiers:
            - claim_history_ref_guid

    CLAIM_HISTORY_POLICY:

      tableName: CLAIM_HISTORY_POLICY
      parent: CLAIM_HISTORY
      parentGuidRef: claim_history_ref_guid
      guidColumn: id
      skipIfEmpty: true
      columns:

        policyNum:
          identifiers:
            - TPCR_POLICY_NO

        productCd:
          identifiers:
            - TPCR_PROCESS

        policyCurrencyCd:
          identifiers:
            -

        productCdVersion:
          identifiers:
            -

        externalProductCd:
          identifiers:
            -

        externalProductVersion:
          identifiers:
            -

        regulatorProductCd:
          identifiers:
            - TPCR_POLICY_NO

        regulatorProductVersion:
          identifiers:
            - T

        planCd:
          identifiers:
            -

        planCdVersion:
          identifiers:
            - claim_guid

        genericGroupCd:
          identifiers:
            -

        planOptionCd:
          identifiers:
            -

        commencementDt:
          identifiers:
            -

        claim_history_ref_guid:
          identifiers:
            - claim_history_ref_guid

    CLIENT:

      tableName: CLIENT

      guidColumn: id

      skipIfEmpty: true

      columns:

        externalClientNum:
          identifiers:
            - TPCR_POLICY_NO

        clientTypeCd:
          identifiers:
            - TPCR_REL_TYPE

        clientNum:
          identifiers:
            - TPCR_ID

      children: []
